### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by YZJ0716** [Castlearchi/Android-StyleGan-Kotlin#1]
Is it possible to control the age, gender, and skin color of the output?

**Comment by Castlearchi** [comment]
No, this app generates random faces. The AI used in this app takes a 512-dimensional tensor as input, which relates to facial characteristics (e.g., age, gender, and skin color). However, I don't know how specific dimensions correspond to attributes like age. Therefore, the AI input is randomized. If you want to control attributes such as age, gender, or skin color, you’ll need to manipulate the 512-dimensional tensor directly or use a different AI model.
